name: Build Debian Package

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # 1. Fetch sources (incl. submodules)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # 2. Cache ccache
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ runner.os }}-

      # 3. System packages required to build, package, and sign
      - name: Install build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            ca-certificates               \
            ccache                         \
            cmake                          \
            debhelper                      \
            devscripts                     \
            libboost-all-dev               \
            libcpprest-dev                 \
            libcurl4-openssl-dev           \
            libssl-dev                     \
            libz-dev                       \
            lsb-release                    \
            openssl                        \
            wget

      # 4. Build & install gRPC v1.60.0 (Ubuntu 24.04 has no official package yet)
      - name: Build gRPC (1.60.0)
        run: |
          git clone --depth 1 --recurse-submodules -b v1.60.0 https://github.com/grpc/grpc /tmp/grpc
          cmake -S /tmp/grpc -B /tmp/grpc/build \
                -DCMAKE_INSTALL_PREFIX=/usr/local \
                -DBUILD_SHARED_LIBS=ON            \
                -DgRPC_INSTALL=ON                 \
                -DgRPC_BUILD_TESTS=OFF            \
                -DgRPC_BUILD_CSHARP_EXT=OFF\
                -DgRPC_BUILD_GRPC_CSHARP_PLUGIN=OFF \
                -DgRPC_BUILD_GRPC_NODE_PLUGIN=OFF \
                -DgRPC_BUILD_GRPC_OBJECTIVE_C_PLUGIN=OFF \
                -DgRPC_BUILD_GRPC_PHP_PLUGIN=OFF \
                -DgRPC_BUILD_GRPC_PYTHON_PLUGIN=OFF \
                -DgRPC_BUILD_GRPC_RUBY_PLUGIN=OFF \
                -DgRPC_BACKWARDS_COMPATIBILITY_MODE=ON \
                -DgRPC_ZLIB_PROVIDER=package      \
                -DgRPC_SSL_PROVIDER=package
          cmake --build /tmp/grpc/build -j"$(nproc)"
          sudo cmake --install /tmp/grpc/build
          sudo ldconfig

      # 5. Configure the project
      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_CXX_STANDARD=17 \
            -DBUILD_ETCD_TESTS=ON   \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      # 6. Build binary & create *.deb with CPack
      - name: Build & package
        run: |
          cmake --build build --config Release -- -j"$(nproc)"
          cmake --build build --target package

      # 7. Upload resulting .deb artefacts
      - name: Upload Deb package
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: build/*.deb

      # 8. Show ccache statistics even if the job fails
      - name: ccache stats
        if: always()
        run: ccache --show-stats
