name: Build etcd-cpp-apiv3 on Ubuntu 24.04

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout_code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: 安装构建依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libboost-all-dev \
            libssl-dev \
            libcpprest-dev \
            pkg-config \
            cpack \
            fakeroot \
            checkinstall

      - name: 构建并安装 gRPC
        run: |
          git clone --recurse-submodules -b v1.60.0 https://github.com/grpc/grpc /opt/grpc
          cd /opt/grpc
          mkdir -p cmake/build && cd cmake/build
          cmake -D CMAKE_INSTALL_PREFIX=/usr/local ../..
          make -j$(nproc)
          sudo make install

      - name: 构建 etcd-cpp-apiv3
        run: |
          mkdir -p build && cd build
          cmake ..
          make -j$(nproc)

      - name: 打包构建产物为 etcd_api.tar.gz
        run: |
          cd build
          tar -czf ../etcd_api.tar.gz *

      - name: 生成 .deb 安装包
        run: |
          cd build
          sudo checkinstall --pkgname=etcd-cpp-api --pkgversion=1.0 --backup=no --deldoc=yes --fstrans=no --install=no --default

      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: etcd-cpp-api-artifacts
          path: |
            etcd_api.tar.gz
            build/*.deb
